FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

COPY *.csproj .

# Install required Linux packages
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    gnupg

# Download Chrome package
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
>> /etc/apt/sources.list.d/google.list'
# Install Chrome
RUN apt-get update && apt-get install -y google-chrome-stable

#Latest Chrome installed, Selenium Manager fetches matching driver automatically

# Restore and build project
RUN dotnet restore
RUN dotnet build

CMD ["dotnet", "test"]